image: docker:latest
services:
  - docker:dind
build:
  stage: build
  script:
    - docker-compose -f test/docker-compose.test.yml -p ci kill
    - docker-compose -f test/docker-compose.test.yml -p ci rm -f
